config/routes.rb
Rails.application.routes.draw do
  get 'tweets/not_logged_in', to: 'tweets#not_logged_in'
  get 'relationships/create'
  get 'relationships/destroy'
  resources :tweets
  get 'sessions/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users ,only: [:new, :create, :update, :edit]
  root :to => 'tweets#index'
  post 'tweets/:id', to:'tweets#create'
  # resources :likes ,only: [:destroy] 

  delete 'tweets/:tweet_id/likes', to: 'likes#destroy' 
  resources :tweets do
    resources :likes, only: [:create, :destroy]
  end 

  resources :users do
    resources :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
    get :search, on: :collection
  end 
  delete 'users/:user_id/relationships', to: 'relationships#destroy' 

  get 'users/:id/followings' => 'users#followings'
  get 'users/:id/followers' => 'users#followers'

  resources :searchs, only: [:index]

  post 'searchs', to: 'searchs#user'
  get 'searchs/user', to:'searchs#user'
 # get

  
end

app/models/relationship.rb
class Relationship < ApplicationRecord
    belongs_to :following, class_name: "User"
    belongs_to :follower, class_name: "User"
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    @user = User.find(params[:user_id])
    follow = current_user.active_relationships.build(follower_id: params[:user_id])
    follow.save
  end

  def destroy
    @user = User.find(params[:user_id])
    follow = current_user.active_relationships.find_by(follower_id: params[:user_id])
    follow.destroy
  end
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/relationships/_follow.html.erb
<% if user.followed_by?(current_user) %>
    <%=link_to "フォロー済み", user_relationships_path(user.id), method: :delete,remote: true %>
<% else %>
    <%=link_to "フォローする", user_relationships_path(user.id), method: :post, remote: true %>
<% end %>

app/views/relationships/create.js.erb
$('#follows_buttons_<%= @user.id %>').html("<%= j(render partial: 'relationships/follow', locals: {user: @user}) %>");

app/views/relationships/destroy.js.erb
$('#follows_buttons_<%= @user.id %>').html("<%= j(render partial: 'relationships/follow', locals: {user: @user}) %>");