config/routes.rb
Rails.application.routes.draw do
  get 'tweets/not_logged_in', to: 'tweets#not_logged_in'
  get 'relationships/create'
  get 'relationships/destroy'
  resources :tweets
  get 'sessions/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users ,only: [:new, :create, :update, :edit]
  root :to => 'tweets#index'
  post 'tweets/:id', to:'tweets#create'
  # resources :likes ,only: [:destroy] 

  delete 'tweets/:tweet_id/likes', to: 'likes#destroy' 
  resources :tweets do
    resources :likes, only: [:create, :destroy]
  end 

  resources :users do
    resources :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
    get :search, on: :collection
  end 
  delete 'users/:user_id/relationships', to: 'relationships#destroy' 

  get 'users/:id/followings' => 'users#followings'
  get 'users/:id/followers' => 'users#followers'

  resources :searchs, only: [:index]

  post 'searchs', to: 'searchs#user'
  get 'searchs/user', to:'searchs#user'
 # get

  
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    belongs_to :user
    has_many :likes
    has_many :like_users, through: :likes, source: :user 
    has_many :replys, class_name: "Tweet", foreign_key: "origintweet_id"
    belongs_to :origintweet, class_name:"Tweet" ,optional: true
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: %i[ show edit update destroy ]
  before_action :logged_in_user, only: [:edit, :update, :destroy]
  # before_action :authenticate_user!

  # GET /tweets or /tweets.json
  def index
    unless logged_in?
      redirect_to "/tweets/not_logged_in"
    end

    if current_user == nil
      @tweets = Tweet.all
    else
      follow = []
      if Relationship.find_by(following_id: current_user.id)
        follow = current_user.followings.pluck(:id)
      end
      follow.push(current_user.id)
      @tweets = Tweet.where(user_id: follow)
    end
    @tweets = @tweets.order(created_at: :desc)
    @users = User.all
  end

  # GET /tweets/1 or /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new(user_id: current_user.id)
    @user = current_user
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets or /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.user_id = current_user.id

    if(params[:id] != nil)
      @tweet.origintweet_id = params[:id]
    end
    

   

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to root_url, notice: "Tweet was successfully created." }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1 or /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: "Tweet was successfully updated." }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1 or /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: "Tweet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def not_logged_in
    render :layout => "not_logged.html.erb"
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_tweet
    @tweet = Tweet.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def tweet_params
    params.require(:tweet).permit(:user_id, current_user.id, :letter)
  end
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/_form.html.erb
<%= form_with(model: tweet, local: true) do |form| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= form.label :letter %>
    <%= form.text_area :letter %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tweets/_letter.html.erb
<tr>
<td><%= link_to tweet.user.name,  tweet.user %></td>
<td><%= link_to tweet.letter, tweet %></td>
<% if tweet.user_id == current_user.id %>
<td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
<td><%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
<% end %>
<td>
    <div id="likes_buttons_<%= tweet.id %>">
    <%= render partial: 'likes/like', locals: { tweet: tweet} %>
    </div>
</td>
<td>
<%= image_tag('reply.png', :size => '30x30')%>
<%= tweet.replys.count %>
</td>

</tr>

app/views/tweets/_logged_in.html.erb
<p id="notice"><%= notice %></p>



<body>
      <h2 id="center">タイムライン</h2>
      <table>
        <thead>
          <tr>
            <th>id</th>
            <th>みんなのツイート</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <%if @tweets == [] %>
          <tr>
            <td>ツイートをしましょう</td>
          </tr>
          <%else%>
          <% @tweets.each do |tweet| %>
          
          
            <%= render 'letter', tweet: tweet %>
          <% end %>
          <%end%>
        </tbody>
      </table>
    </div>


    <br>
</body>

app/views/tweets/_not_logged_in.html.erb
<p id="textbig">タスクの管理ができるアプリです。利用するにはログインしてください。</p>
<div class="midle" id="center">

<p id="textbig" id="center">ログイン</p>
<%= link_to "ログイン", login_path%>
<br>
<%= link_to login_path do image_tag('login.png',:size => '240x60' , onmouseover: "this.src='#{asset_path('login2.png')}'" ,onmouseout: "this.src='#{asset_path('login.png')}'") end %>
<br>
<br>
<%= link_to new_user_path do image_tag('first.png',:size => '240x60' , onmouseover: "this.src='#{asset_path('first2.png')}'" ,onmouseout: "this.src='#{asset_path('first.png')}'") end %>
<br>

</div>
<p id="center">メールアドレスパスワードをお忘れ方</p>
<p id="center">パスワード変更</p>

app/views/tweets/_replyfrom.html.erb
<%= form_with(model: tweet, local: true, url:origin.id.to_s ,method: :post) do |form| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= form.label :reply %>
    <%= form.text_area :letter %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>
<p>編集してください</p>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<% if logged_in? %>
  <%= render 'tweets/logged_in' %>
<% end %>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>
<p>呟きたいことを書いてください</p>

<%= render 'form', tweet: @tweet %>



<%= link_to 'Back', tweets_path %>

app/views/tweets/not_logged_in.html.erb
<p id="textbig">nokotta-です。利用するにはログインしてください。</p>
<div class="midle" id="center">


<br>
<div id="mannaka">
<%= link_to login_path do image_tag('login.png',:size => '240x60' , onmouseover: "this.src='#{asset_path('login2.png')}'" ,onmouseout: "this.src='#{asset_path('login.png')}'") end %>
<br>
<br>
<%= link_to new_user_path do image_tag('first.png',:size => '240x60' , onmouseover: "this.src='#{asset_path('first2.png')}'" ,onmouseout: "this.src='#{asset_path('first.png')}'") end %>
<br>
</div>

</div>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<% if @tweet.origintweet != nil%>
<%= link_to @tweet.origintweet.user.name , @tweet.origintweet.user%>
<%= link_to @tweet.origintweet.letter , @tweet.origintweet%>


<%end%>


<p id=textLittleBig>
  <%= link_to @tweet.user.name , @tweet.user%>
</p>

<p id=textbig>
  <%= @tweet.letter %>
</p>
 <div id="likes_buttons_<%= @tweet.id %>">
    <%= render partial: 'likes/like', locals: { tweet: @tweet} %>
</div>

  <!--<%= @tweet.replys.count%>-->
  <% @tweet.replys.each do |reply| %>
  <table>
    <%= render 'letter', tweet: reply %>
  </table>
  <%end%>


  <%= render 'replyfrom', {tweet: Tweet.new , origin: @tweet}%>
  <%= link_to 'Edit', edit_tweet_path(@tweet) %> |
  <%= link_to 'Back', tweets_path %>