config/routes.rb
Rails.application.routes.draw do
  get 'tweets/not_logged_in', to: 'tweets#not_logged_in'
  get 'relationships/create'
  get 'relationships/destroy'
  resources :tweets
  get 'sessions/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users ,only: [:new, :create, :update, :edit]
  root :to => 'tweets#index'
  post 'tweets/:id', to:'tweets#create'
  # resources :likes ,only: [:destroy] 

  delete 'tweets/:tweet_id/likes', to: 'likes#destroy' 
  resources :tweets do
    resources :likes, only: [:create, :destroy]
  end 

  resources :users do
    resources :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
    get :search, on: :collection
  end 
  delete 'users/:user_id/relationships', to: 'relationships#destroy' 

  get 'users/:id/followings' => 'users#followings'
  get 'users/:id/followers' => 'users#followers'

  resources :searchs, only: [:index]

  post 'searchs', to: 'searchs#user'
  get 'searchs/user', to:'searchs#user'
 # get

  
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :tweets
  has_many :likes

  #関連するツイートを持ってくる
  has_many :like_tweets, through: :likes, source: :tweet
  has_many :follow_tweets, through: :followings, source: :tweet

  #フォロー
  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
  has_many :followings, through: :active_relationships, source: :follower

  #フォロワー
  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
  has_many :followers, through: :passive_relationships, source: :following

  def like?(tweet)
    likes.exists? tweet: tweet
  end

  def followed_by?(user)
    passive_relationships.find_by(following_id: user.id).present?
  end

  def self.search(search)
    return User.none unless search
    User.where(['name LIKE ?', "%#{search}%"])      
  end


end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def new
    @user = User.new()
  end
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @root_url }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name,:email,:password)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new()
    render :layout => "not_logged.html.erb"
  end

  def show
    set_user
    @tweets = @user.tweets.order(created_at: :desc)
    @like_tweets = @user.like_tweets.order(created_at: :desc)
    # @likes = Like.where(user_id: @user.id)
    # @liketweetid = @likes.pluck(:tweet_id)
    # @like_tweets = Tweet.where(id: @liketweetid)
  end

  def update
    @user = User.find(params[:id])
    respond_to do |format|
      if @user.update(comment_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to root_url }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /users/1/edit
  def edit
    set_user
  end

  def followings
    set_user
  end

  def followers
    set_user
  end

  def search
    @users = User.search(params[:user])
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name, :email, :password)
  end

  def comment_params
    params.require(:user).permit(:comment)
  end

  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_comment.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= form.label :comment %>
    <%= form.text_area :comment %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_followList.html.erb
<div>
<%= link_to "back", @user %>
<br>
<%= link_to_unless_current 'フォロー', '/users/' + @user.id.to_s + '/followings' %> | 
<%= link_to_unless_current 'フォロワー', '/users/' + @user.id.to_s + '/followers' %>
</div>
<table>
<tr>
<% followList.each do |f| %>
<td><%= link_to f.name,  f %></td>
<% end %>
</tr>

</table>

app/views/users/_form.html.erb
<%= form_with(model: user,local: true) do |form| %>
    <% if user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>
  
        <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  
  
    <div class="field">
      <%= form.label :name %>
      <%= form.text_area :name %>
    </div>

    <div class="field">
      <%= form.label :email %>
      <%= form.email_field :email %>
    </div>

    <div class="field">
      <%= form.label :password %>
      <%= form.password_field :password %>
    </div>


    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>

app/views/users/edit.html.erb
<h1>Editing Comment</h1>
<p>編集してください</p>

<%= render 'comment', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>
<%- @user.id %>
<%- @user.comment %>

app/views/users/followers.html.erb
<%= render 'followList', followList: @user.followers %>

app/views/users/followings.html.erb
<%= render 'followList', followList: @user.followings %>

app/views/users/new.html.erb
<h1>新規会員登録</h1>
<%= render 'form', user: @user %>
<br>

<%= link_to 'Back', root_url %>

app/views/users/search.html.erb
<p>検索</p>
<%= form_with(url:search_users_path, method: :get, local: true) do |form|%>
  <%= form.search_field(:user) %>
  <%= form.submit :search %>
<% end %>



<ul><% @users.each do |user| %>
  <li>
    <%= link_to user.name, user %>
  </li>
  <% end %>
</ul>

app/views/users/show.html.erb
<h2><span id="textbig"><%= @user.name%></span>
  <font color="gray"> ID:<%=@user.id%></font>
</h2>
<h3>
<%= link_to "フォロー" + @user.followings.count.to_s, '/users/' + @user.id.to_s + '/followings'%> :

<%= link_to "フォロワー" + @user.followers.count.to_s, '/users/' + @user.id.to_s + '/followers'%>




</h3>


<% if current_user == @user %>
<form name="form1" id="id_form1" action="">
    <div id="output"></div>
    <p id="first_text"><%= @user.comment %></p>
    <div id="id_textBox1" style="display:none"></div>
    <%# <input type="button" id="profile" value="変更" onclick="onButtonClick();" /> %>
    
    <%= link_to 'Edit', edit_user_path(@user) %> 

</form>




<% else%>
<% user = @user%>
<div id="follows_buttons_<%=user.id%>">
  <%= render partial: 'relationships/follow', locals:{user: user} %>
</div>
<%end%>



<body>
  <div class="area">
    <input id="tab1" type="radio" name="tab_name" checked>
    <label class="tab_class" for="tab1">ツイート</label>
    <div class="content_class">
      <table>
        <tbody>
          <% @tweets.each do |tweet| %>
          <tr>
            <td><%= link_to tweet.letter, tweet %></td>
            <% if tweet.user_id == current_user.id %>
            <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
            <td><%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% end %>
            <td>
            <div id="likes_buttons_<%= tweet.id %>">
              <%= render partial: 'likes/like', locals: { tweet: tweet} %>
            </div>
            </td>
          </tr>
          
          <% end %>
        </tbody>
      </table>
    </div>
    <input id="tab2" type="radio" name="tab_name">
    <label class="tab_class" for="tab2">いいね</label>
    <div class="content_class">
      <table>
        <tbody>
          <% if @like_tweets == []%>
          <tr>
            <td>ここにいいねした一覧が表示されます</td>
          </tr>
          <%else%>
          <% @like_tweets.each do |tweet| %>
          <tr>
            <td><%= link_to tweet.letter, tweet %></td>
            <% if tweet.user_id == current_user.id %>
            <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
            <td><%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% end %>
            <td>
              <div id="likes_buttons_<%= tweet.id %>">
                <%= render partial: 'likes/like', locals: { tweet: tweet} %>
              </div>
            </td>
          </tr>
          <% end %>
          <%end%>
        </tbody>

      </table>
    </div>
  </div>
</body>